name: expenses_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.62.0
  go_router: ^6.5.7
  font_awesome_flutter: ^10.4.0
  flutter_credit_card: ^3.0.6
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
